# **A look into the ENIAC Data**

Here the remaining four datasets will be explored

In [1]:
import pandas as pd

## Exploring the products csv file

In [19]:
# import
url = "https://drive.google.com/file/d/1mbJgcLmn8OT-V3yJLgh3D5J50RV411sP/view?usp=drive_link" # products.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
product_df = pd.read_csv(path)

In [20]:
#looking at the dataframe structure and features
product_df.info()
product_df.shape
product_df.describe(include='all')
#to have  a look at what the data looks like, tail could also be used
product_df.head()
# looking at how many unique
product_df['sku'].str[:3].nunique()
#looking for any NaN values
product_df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19326 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          19326 non-null  object
 1   name         19326 non-null  object
 2   desc         19319 non-null  object
 3   price        19280 non-null  object
 4   promo_price  19326 non-null  object
 5   in_stock     19326 non-null  int64
 6   type         19276 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.0+ MB

sku             0
name            0
desc            7
price          46
promo_price     0
in_stock        0
type           50
dtype: int64

In [22]:
# looking at whether the promo price is always smaller than the price
(product_df['price'] > product_df['promo_price']).sum()
(product_df['price'] == product_df['promo_price']).sum()

np.int64(228)

In [23]:
# looking at whether the non numeric columns can be converted
product_df['price'] = pd.to_numeric(product_df['promo_price'])

ValueError: Unable to parse string "1.119.976" at position 50

In [24]:
# looking for NaN values
#product_df['type'].unique()
#product_df.index[product_df['type'].isna()]
product_df.loc[product_df['type'].isna(), 'type']

307      NaN
530      NaN
792      NaN
797      NaN
798      NaN
1193     NaN
1199     NaN
1200     NaN
1201     NaN
1202     NaN
1203     NaN
1280     NaN
1281     NaN
1282     NaN
1283     NaN
1759     NaN
1899     NaN
3016     NaN
3055     NaN
3090     NaN
3106     NaN
3107     NaN
3108     NaN
3110     NaN
3112     NaN
3114     NaN
3116     NaN
3117     NaN
3118     NaN
3119     NaN
3120     NaN
3121     NaN
3122     NaN
3123     NaN
3124     NaN
3125     NaN
3126     NaN
3138     NaN
10864    NaN
11766    NaN
11767    NaN
11768    NaN
11770    NaN
11771    NaN
15932    NaN
18741    NaN
18822    NaN
18838    NaN
19092    NaN
19185    NaN
Name: type, dtype: object

In [25]:
# looking for any duplicate rows
product_df[product_df.duplicated()]

,sku,name,desc,price,promo_price,in_stock,type
101,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
102,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
103,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
104,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
105,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
...,...,...,...,...,...,...,...
16831,APP2302,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13-inch Core i5 Touch Bar 33 G...,26.155.941,26.155.941,0,"1,02E+12"
16833,APP2303,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13 inch Touch Bar 33 GHz Core ...,237.559.421,23.755.942,0,"1,02E+12"
18190,PAR0077,Parrot Bebop Drone 2 Power,Drone cuadricóptero quality camera integrated ...,699.9,6.733.892,0,11905404
18308,NKI0010,Nokia Wireless sphygmomanometer Plata,Sphygmomanometer for iPhone iPad and iPod App.,129.99,1.149.899,1,11905404
18514,PLA0035,Bluetooth Headset Plantronics Explorer 80,egonómico wireless headset design for iPhone i...,39.99,349.896,1,5384

## Exploring the orders csv file

In [6]:
# import
url = "https://drive.google.com/file/d/1J-XJS9NS6fXH-dA9KEurAJ-MqNhVJqEE/view?usp=drive_link" # orders.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orders_df = pd.read_csv(path)

In [26]:
# looking at the data
orders_df.head()
orders_df.info()
orders_df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226909 entries, 0 to 226908
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226909 non-null  int64
 1   created_date  226909 non-null  datetime64[ns]
 2   total_paid    226904 non-null  float64
 3   state         226909 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 6.9+ MB

order_id        0
created_date    0
total_paid      5
state           0
dtype: int64

In [7]:
# looking at the orders status and dominance
#orders_df.loc[orders_df['total_paid'].isna(),:]
orders_df.loc[~(orders_df['state'].isin(['Completed'])),:].shape[0]

180304

In [27]:
# looking at what typical order values are
#orders_df.loc[(orders_df['total_paid']== 0.000000) & (orders_df['state'] == 'Completed'),:].shape[0]
#orders_df.loc[(orders_df['total_paid']== 214747.530000),:]
orders_df.loc[orders_df['state'] == 'Completed',:].nlargest(10,'total_paid')

        order_id        created_date  total_paid      state
147938    448053 2017-11-27 12:59:51    13387.78  Completed
95399     394981 2017-08-31 13:09:05    10586.97  Completed
40247     339735 2017-03-27 16:57:34     9987.76  Completed
34178     333662 2017-04-12 13:33:22     9423.90  Completed
133774    433435 2017-11-24 12:17:33     9080.16  Completed
145412    445507 2017-11-26 16:07:32     8287.80  Completed
105912    405497 2017-09-29 10:57:59     7376.58  Completed
197428    497912 2018-01-25 12:01:03     7268.58  Completed
14679     314158 2017-01-24 10:37:13     7230.97  Completed
84728     384303 2017-07-31 08:50:26     7216.77  Completed

In [28]:
# checking if the dates can be converted to datetime
orders_df['created_date'] = pd.to_datetime(orders_df['created_date'])

In [29]:
# looking for duplicates
orders_df[orders_df.duplicated()]

Empty DataFrame
Columns: [order_id, created_date, total_paid, state]
Index: []

## Exploring the brands csv file

In [15]:
# import the data
url = "https://drive.google.com/file/d/1itjfSCQVkxsJKSuiUNvJ8HJFKENkFZt6/view?usp=drive_link" # brands.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
brands_df = pd.read_csv(path)

In [30]:
# looking at the structure of the dataframe
brands_df.shape
brands_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   short   187 non-null    object
 1   long    187 non-null    object
dtypes: object(2)
memory usage: 3.1+ KB

In [31]:
# counting number of brands
brands_df['short'].nunique()

187

In [32]:
# checking if there are NaN values
brands_df.isna().sum()

short    0
long     0
dtype: int64

In [33]:
# checking if there are duplicates
brands_df[brands_df.duplicated()]

Empty DataFrame
Columns: [short, long]
Index: []

In [16]:
product_df['sku'].str[:3].nunique() == brands_df['short'].nunique()

False

## Exploring the orderlines csv file

In [34]:
#import
url = "https://drive.google.com/file/d/1LyNo5EZIB0LUJvkrWzsgRsGuVwvnSMBQ/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines_df = pd.read_csv(path)